name: CI
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run env:check
        env:
          APP_URL: https://example.test
          PORT: 8080
          DATABASE_URL: postgres://user:pass@localhost/db
          SHOPIFY_API_KEY: test
          SHOPIFY_API_SECRET: test
          SHOPIFY_SCOPES: read_customers,write_customers
          WEBHOOK_SECRET: test
          JWT_SECRET: this_is_long_enough_for_ci_only
          ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
          MITTO_API_URL: https://example.test
          MITTO_API_KEY: test
          QUEUE_DRIVER: memory
          NODE_ENV: test
      - run: npm run lint
      - run: npm run format:check
      - run: npm run prisma:generate
      - run: npm run prisma:validate
      - run: npm run test
      - run: npm run openapi:lint
